---
# tasks file for apache-maven
- name: Checking if Maven is already installed
  stat: 
    path: '{{ maven_home_parent_directory }}/maven'
  register: maven_installed

- name: Downloading Maven Binaries
  get_url:
    url: '{{ maven_download_url }}'
    dest: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
    url_username: '{{ maven_download_username }}'
    url_password: '{{ maven_download_password }}'
  when: not maven_installed.stat.exists

- name: Unarchive Maven Binaries
  unarchive:
    src: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
    dest: '{{ maven_home_parent_directory }}'
    copy: no
  when: not maven_installed.stat.exists

- name: change the folder name
  shell: "mv {{ maven_home_parent_directory }}/{{ maven_file_name }} {{ maven_home_parent_directory }}/maven"

- name: Remove old path configuration
  file:
    path: /etc/profile.d/maven.sh
    state: absent

- name: Maven path configuration
  lineinfile:
    dest: /etc/profile.d/maven.sh
    line: '{{ item.line }}'
    create: yes
    state: present
  with_items:
    - { line: 'M2_HOME={{ maven_home_parent_directory }}/maven' }
    - { line: 'PATH=$PATH:$M2_HOME/bin' }

- name: Cleaning Up
  file:
    state: absent
    path: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
